package com.dandelion.membership.dao.model;

import java.util.Date;

public class IDLAppCollection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_idl_app_collection.ID
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_idl_app_collection.app_id
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_idl_app_collection.collection_id
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    private Long collectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_idl_app_collection.CreatedDate
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    private Date createddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_idl_app_collection.ModifiedDate
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    private Date modifieddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_idl_app_collection.ID
     *
     * @return the value of tb_idl_app_collection.ID
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_idl_app_collection.ID
     *
     * @param id the value for tb_idl_app_collection.ID
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_idl_app_collection.app_id
     *
     * @return the value of tb_idl_app_collection.app_id
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_idl_app_collection.app_id
     *
     * @param appId the value for tb_idl_app_collection.app_id
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_idl_app_collection.collection_id
     *
     * @return the value of tb_idl_app_collection.collection_id
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public Long getCollectionId() {
        return collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_idl_app_collection.collection_id
     *
     * @param collectionId the value for tb_idl_app_collection.collection_id
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public void setCollectionId(Long collectionId) {
        this.collectionId = collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_idl_app_collection.CreatedDate
     *
     * @return the value of tb_idl_app_collection.CreatedDate
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public Date getCreateddate() {
        return createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_idl_app_collection.CreatedDate
     *
     * @param createddate the value for tb_idl_app_collection.CreatedDate
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_idl_app_collection.ModifiedDate
     *
     * @return the value of tb_idl_app_collection.ModifiedDate
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public Date getModifieddate() {
        return modifieddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_idl_app_collection.ModifiedDate
     *
     * @param modifieddate the value for tb_idl_app_collection.ModifiedDate
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }
}