package com.dandelion.membership.dao.model;

import java.util.Date;

public class IDLApp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_idl_app.ID
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_idl_app.user_id
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_idl_app.url
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_idl_app.title
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_idl_app.CreatedDate
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    private Date createddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_idl_app.ModifiedDate
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    private Date modifieddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_idl_app.ID
     *
     * @return the value of tb_idl_app.ID
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_idl_app.ID
     *
     * @param id the value for tb_idl_app.ID
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_idl_app.user_id
     *
     * @return the value of tb_idl_app.user_id
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_idl_app.user_id
     *
     * @param userId the value for tb_idl_app.user_id
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_idl_app.url
     *
     * @return the value of tb_idl_app.url
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_idl_app.url
     *
     * @param url the value for tb_idl_app.url
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_idl_app.title
     *
     * @return the value of tb_idl_app.title
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_idl_app.title
     *
     * @param title the value for tb_idl_app.title
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_idl_app.CreatedDate
     *
     * @return the value of tb_idl_app.CreatedDate
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public Date getCreateddate() {
        return createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_idl_app.CreatedDate
     *
     * @param createddate the value for tb_idl_app.CreatedDate
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_idl_app.ModifiedDate
     *
     * @return the value of tb_idl_app.ModifiedDate
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public Date getModifieddate() {
        return modifieddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_idl_app.ModifiedDate
     *
     * @param modifieddate the value for tb_idl_app.ModifiedDate
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }

}