package com.dandelion.membership.dao.model;

import java.util.Date;

public class UrlCollection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_url_collection.ID
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_url_collection.URL
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_url_collection.Type
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_url_collection.CreatedDate
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    private Date createddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_url_collection.ModifiedDate
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    private Date modifieddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_url_collection.ID
     *
     * @return the value of tb_url_collection.ID
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_url_collection.ID
     *
     * @param id the value for tb_url_collection.ID
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_url_collection.URL
     *
     * @return the value of tb_url_collection.URL
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_url_collection.URL
     *
     * @param url the value for tb_url_collection.URL
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_url_collection.Type
     *
     * @return the value of tb_url_collection.Type
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_url_collection.Type
     *
     * @param type the value for tb_url_collection.Type
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_url_collection.CreatedDate
     *
     * @return the value of tb_url_collection.CreatedDate
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    public Date getCreateddate() {
        return createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_url_collection.CreatedDate
     *
     * @param createddate the value for tb_url_collection.CreatedDate
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_url_collection.ModifiedDate
     *
     * @return the value of tb_url_collection.ModifiedDate
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    public Date getModifieddate() {
        return modifieddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_url_collection.ModifiedDate
     *
     * @param modifieddate the value for tb_url_collection.ModifiedDate
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }
}