package com.dandelion.membership.dao.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.ID
     *
     * @mbggenerated Sun May 18 16:21:46 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.CreatedDate
     *
     * @mbggenerated Sun May 18 16:21:46 CST 2014
     */
    private Date createddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.ModifiedDate
     *
     * @mbggenerated Sun May 18 16:21:46 CST 2014
     */
    private Date modifieddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.ID
     *
     * @return the value of tb_user.ID
     * @mbggenerated Sun May 18 16:21:46 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.ID
     *
     * @param id the value for tb_user.ID
     * @mbggenerated Sun May 18 16:21:46 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.CreatedDate
     *
     * @return the value of tb_user.CreatedDate
     * @mbggenerated Sun May 18 16:21:46 CST 2014
     */
    public Date getCreateddate() {
        return createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.CreatedDate
     *
     * @param createddate the value for tb_user.CreatedDate
     * @mbggenerated Sun May 18 16:21:46 CST 2014
     */
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.ModifiedDate
     *
     * @return the value of tb_user.ModifiedDate
     * @mbggenerated Sun May 18 16:21:46 CST 2014
     */
    public Date getModifieddate() {
        return modifieddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.ModifiedDate
     *
     * @param modifieddate the value for tb_user.ModifiedDate
     * @mbggenerated Sun May 18 16:21:46 CST 2014
     */
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }

}