package com.dandelion.membership.dao.data;

import com.dandelion.membership.dao.model.IDLApp;
import com.dandelion.membership.dao.model.IDLAppExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IDLAppMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_idl_app
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    int countByExample(IDLAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_idl_app
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    int deleteByExample(IDLAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_idl_app
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_idl_app
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    int insert(IDLApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_idl_app
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    int insertSelective(IDLApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_idl_app
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    List<IDLApp> selectByExample(IDLAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_idl_app
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    IDLApp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_idl_app
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    int updateByExampleSelective(@Param("record") IDLApp record, @Param("example") IDLAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_idl_app
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    int updateByExample(@Param("record") IDLApp record, @Param("example") IDLAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_idl_app
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    int updateByPrimaryKeySelective(IDLApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_idl_app
     *
     * @mbggenerated Sun May 18 21:15:59 CST 2014
     */
    int updateByPrimaryKey(IDLApp record);
}