package com.dandelion.membership.dao.data;

import com.dandelion.membership.dao.model.Thing;
import com.dandelion.membership.dao.model.ThingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ThingMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thing
	 * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
	 */
	int countByExample(ThingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thing
	 * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
	 */
	int deleteByExample(ThingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thing
	 * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thing
	 * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
	 */
	int insert(Thing record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thing
	 * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
	 */
	int insertSelective(Thing record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thing
	 * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
	 */
	List<Thing> selectByExample(ThingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thing
	 * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
	 */
	Thing selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thing
	 * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Thing record,
			@Param("example") ThingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thing
	 * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
	 */
	int updateByExample(@Param("record") Thing record,
			@Param("example") ThingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thing
	 * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
	 */
	int updateByPrimaryKeySelective(Thing record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thing
	 * @mbggenerated  Sat Dec 27 15:02:10 CST 2014
	 */
	int updateByPrimaryKey(Thing record);
}