package com.dandelion.membership.dao.data;

import com.dandelion.membership.dao.model.UrlCollection;
import com.dandelion.membership.dao.model.UrlCollectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UrlCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url_collection
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    int countByExample(UrlCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url_collection
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    int deleteByExample(UrlCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url_collection
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url_collection
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    int insert(UrlCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url_collection
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    int insertSelective(UrlCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url_collection
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    List<UrlCollection> selectByExample(UrlCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url_collection
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    UrlCollection selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url_collection
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    int updateByExampleSelective(@Param("record") UrlCollection record, @Param("example") UrlCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url_collection
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    int updateByExample(@Param("record") UrlCollection record, @Param("example") UrlCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url_collection
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    int updateByPrimaryKeySelective(UrlCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_url_collection
     *
     * @mbggenerated Sun Apr 27 14:51:14 CST 2014
     */
    int updateByPrimaryKey(UrlCollection record);
}